apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
    - name: my-container
      image: my-image:latest 
      securityContext:
        # Run container as non-root user
        runAsUser: 1000 
        runAsGroup: 3000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_BIND_SERVICE
        readOnlyRootFilesystem: true
  securityContext:
    hostPID: false
    hostNetwork: false
    hostIPC: false